plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'site.tradelink'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url 'https://projectlombok.org/edge-releases' }  // 추가
}

dependencies {
	// web
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// lombok
	compileOnly 'org.projectlombok:lombok:edge-SNAPSHOT'
	annotationProcessor 'org.projectlombok:lombok:edge-SNAPSHOT'

	testCompileOnly 'org.projectlombok:lombok:edge-SNAPSHOT'
	testAnnotationProcessor 'org.projectlombok:lombok:edge-SNAPSHOT'

	// validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// mysql
	runtimeOnly 'com.mysql:mysql-connector-j'

	// Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'

	// jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// security
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// webflux for webclient
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//S3
	implementation 'software.amazon.awssdk:s3:2.27.21'

	// eventListener
	implementation 'org.springframework.retry:spring-retry:2.0.12'
	implementation 'org.springframework:spring-aop'
	implementation 'org.aspectj:aspectjweaver'

	// Monitoring
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-registry-prometheus'

    // WebSocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    implementation "io.awspring.cloud:spring-cloud-aws-starter-parameter-store:3.4.0"
}

tasks.named('test') {
	useJUnitPlatform()
}
